### ISSUE TITLE
Unable to download file of published dataset (DOI: 10.5061/dryad.s38kf65)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3290] opened 2024-04-08 13:24 UTC
[Data from: Genome-wide association meta-analysis of functional outcome after ischemic stroke](https://datadryad.org/stash/dataset/doi:10.5061/dryad.s38kf65)
DOI: 10.5061/dryad.s38kf65

Download is initiated but not completed. Please investigate.

**Comment by ahamelers** [comment] 2024-04-08 13:29
I can't recreate this—what browser etc.?

**Comment by ahamelers** [comment] 2024-04-17 16:47
@jleighherzog ping 😄

**Comment by ahamelers** [comment] 2024-07-19 11:32
Duplicate of #3526

**Closed by ahamelers** 2024-07-19 11:32 UTC
Labels: bug, Download, Curator Fix
