### ISSUE TITLE
Replace TinyMCE

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3060] opened 2024-01-10 22:49 UTC
TinyMCE is nice, but there is no need for us to maintain two rich text editors. Adapt the README editor to be used in the places where TinyMCE is currently used.

Note that the README editor saves as Markdown, while TinyMCE saves as HTML. Is it easy to save as HTML from the README editor? Or will we need to change a lot of stored metadata?

**Comment by ahamelers** [comment] 2024-01-11 11:08
The Markdown editor can very easily output and save HTML. 

The question for use of the markdown editor in place of TinyMCE is what features of the TinyMCE editor do users, and particularly curators, use (highlighting? special characters, etc.?), specifically what are the must-haves, that we should try to replicate in the other editor?

**Comment by ahamelers** [comment] 2024-04-17 16:54
Duplicate of #2977

**Closed by ahamelers** 2024-04-17 16:54 UTC
