### ISSUE TITLE
Integration: Canadian Science Publishing

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3284] opened 2024-04-05 02:52 UTC
Please add/update the journal models with the information described in the [CSP spreadsheet](https://docs.google.com/spreadsheets/d/1QyDVBWSR2OrivpKK_fbTtVr7_Klq5Rm2zRuoTGTbAtg/edit?usp=sharing).

Consult with Maria about whether there is an associated payment plan.

**Comment by ahamelers** [comment] 2024-04-15 13:52
Is this a duplicate of #3187?

**Comment by jleighherzog** [comment] 2024-04-23 16:39
All journals should be configured to automatically be placed in PPR status upon submission:
- FACETS
- Arctic Science
- Drone Systems and Applications
- Canadian Journal of Fisheries and Aquatic Sciences

CSP will send through metadata that includes '**rejected**' and '**withdrawn**' decision terms. Please configure our site to auto-withdraw the related datasets that have these decision terms attached.

**Comment by jleighherzog** [comment] 2024-04-23 16:43
Confirming that Judy Hum-Delaney has been set up with Admin access and permissions for the 4 journal titles.

**Comment by ahamelers** [comment] 2024-04-23 17:10
> Confirming that Judy Hum-Delaney has been set up with Admin access and permissions for the 4 journal titles.

This user has access to all the journals on the publisher ('org_admin') level

**Comment by ahamelers** [comment] 2024-04-23 17:16
All the journals are set to 'default to ppr'

**Comment by ryscher** [comment] 2024-04-30 14:19
Added journal codes to the DB. CSP will be using the "automatic prefill" links, which match based on the journal code instead of ISSN, so they are needed.

Prefill links look like: 
http://datadryad.org/submit?journalID=some_code&manu=ABCD-2024-0985

**Closed** 2024-05-07 12:00 UTC
Labels: new journal
