### ISSUE TITLE
Zenodo cleanup

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3076] opened 2024-01-17 16:56 UTC
There are many un-replicated datasets that are waiting to go to Zenodo. Most of these could replicate, with appropriate babysitting. Do we need to replicate these? Or should we give up on them?

**Comment by ahamelers** [comment] 2024-04-17 17:46
Duplicate of #3154

**Closed by ahamelers** 2024-04-17 17:46 UTC
Labels: Tech Debt
