### ISSUE TITLE
Duplicate publicationISSNs

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2837] opened 2023-09-25 18:37 UTC
The publicationISSN field in Internal Metadata was intended to only have one value per dataset. Some datasets have multiples. Curators have noticed that many multiples were introduced on 2023-2-20. This may have been the result of running an import process.

Determine whether we can reliably clean up these values by removing any duplicates introduced on 2023-2-20.

**Comment by ahamelers** [comment] 2024-07-25 14:27
Duplicate of #2321 and made obsolete by #2024

**Closed by ahamelers** 2024-07-25 14:27 UTC
Labels: Tech Debt
