### ISSUE TITLE
Create Force Delete option for Superusers

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2851] opened 2023-10-03 14:56 UTC
**Priority**: Low
**Impact**: Superusers will be able to withdraw/remove datasets "In Progress"

Curators (specifically, Superusers) would benefit from having the option to remove/withdraw data submissions that are "In Progress" **AND** have never been fully submitted. If a dataset was never fully submitted = no checkpoints were created. And, without checkpoints created, curators need to use the Force Edit feature to enter editing mode and provide the required metadata and/or files in order to rebuild and finally withdraw. This costs time. _Note: Authors can remove unsubmitted datasets, however, they rarely follow through with the instructions provided._ 

In our meeting, it was suggested that this option be made available near the Force Edit feature within the Activity Log. 

@bryanmgee : Do we need to set up an automatic notification when submissions are removed/withdrawn? Or are responses usually handled via Salesforce?

**Comment by bryanmgee** [comment] 2023-10-03 16:59
I don't think there's a need to have an automated notification; even when people ask for withdrawals and we can't actually do it b/c of this In Progress obstacle right now, no one has ever followed up to be like "hey I thought you guys withdrew it" because they don't get any email notifications like PPR reminders. Also because the withdrawn email probably says something about being able to reinstate, but there's literally nothing they can do if a never-completed one is deleted

**Comment by ahamelers** [comment] 2024-12-21 21:32
Duplicate of #2032

**Closed by ahamelers** 2024-12-21 21:32 UTC
Labels: Curator Feature
