### ISSUE TITLE
Wildlife Biology - fix metadata so the import button can work on this specific dataset

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3593] opened 2024-08-21 00:36 UTC
Wildlife Bio has not updated their template yet, and we have an author trying to use the Import Metadata button, but it's not working. 

It's resource id 311972 and the manuscript ID is WLB-2024-01295.R3. Let me know if you need anything else.

**Comment by ahamelers** [comment] 2024-08-21 11:54
It looks like there are 135 manuscripts in our system where the manuscript number starts with `WLB-` but due to the bad template the matched journal is Ecography, instead of Wildelife Biology. I've gone ahead and fixed the journal for all of these.

Any idea when the template will be fixed so we don't have to keep doing this?

**Closed by ahamelers** 2024-08-21 11:54 UTC
Labels: Curator Fix

**Comment by jleighherzog** [comment] 2024-11-26 13:07
Received a notification today that another template on their side has been edited! Should work now.

**Comment by jleighherzog** [comment] 2025-01-06 21:26
Working properly! Confirmed.
