### ISSUE TITLE
Author affiliation UWSOM changes to WUSOM on the landing page

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3423] opened 2024-06-12 14:08 UTC
**Bug description:**
The author affiliation should be “University of Washington School of Medicine”, and you can select it from the drop-down menu. However, on the review page, it says "Washington University School of Medicine", which is a totally different institution. An author sent this to HD, and I confirmed it in Sandbox. Audrey confirmed on Sandbox, but then said it works as expected on her local machine.

This is the dataset where the bug was identified:
doi:10.5061/dryad.d2547d89h
Resource ID: 293799

**Comment by ahamelers** [comment] 2024-06-12 14:22
Bug confirmed on sandbox and production, however it is not occurring locally or on dev. A database problem?

**Comment by ahamelers** [comment] 2024-07-11 18:41
Also, the (bad) ROR is in the affiliation correctly despite the wrong name! I will also work to figure out how the bad name came into it 🤔

**Comment by ahamelers** [comment] 2024-07-11 18:55
Looks like some historic affiliation got set with the wrong name, at some point 🤷 . This is fixed in the database. We'll handle the fact the ROR has been withdrawn in another ticket.

**Closed by ahamelers** 2024-07-11 18:55 UTC
Labels: bug, Curator Fix
